apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: apps
  labels:
    app: node-app
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP