apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-node-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/paolocarta/tf-kind-argocd-node-docker'
    targetRevision: HEAD
    path: app-manifests/my-node-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true